logback:
  amqp:
    exchange: task-manager-logs-exchange
    routing-key: "#"

spring:
  application:
    name: gridcapa-core-cc-adapter
  rabbitmq:
    username: gridcapa
    password: gridcapa
    host: localhost
    port: 5672
  cloud:
    stream:
      default:
        group: core-cc-adapter
      bindings:
        consumeTaskDtoUpdate-in-0:
          destination: core-cc-task-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
        bindings:
          consumeTaskDtoUpdate-in-0:
            consumer:
              binding-routing-key: input
    function:
      definition: consumeTaskDtoUpdate

minio-adapter:
  bucket: gridcapa
  base-path:
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000

job-launcher:
  auto-trigger-filetypes:
    - RAOREQUEST
  url:
    task-manager-timestamp-url: http://localhost:8080/tasks/
    task-manager-business-date-url: http://localhost:8080/tasks/businessdate/
  process:
    timezone: CET
    days-to-add: 0

core-cc-adapter:
  whitelist:
    - http://localhost:9000
    - http://minio:9000
    - file:/

core-cc-runner:
  amqp:
    queue-name: core-cc-requests

server:
  port: ${CORE_CC_ADAPTER_SERVER_PORT:8080}
