spring:
  rabbitmq:
    username: gridcapa
    password: gridcapa
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        consumeTask-in-0:
          binder: rabbit
          destination: core-cc-run-task
          group: core-cc
        consumeAutoTask-in-0:
          binder: rabbit
          destination: core-cc-run-task-auto
          group: core-cc
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
    function:
      definition: consumeTask;consumeAutoTask

core-cc-runner:
  amqp:
    queue-name: core-cc-requests

server:
  port: ${CORE_CC_ADAPTER_SERVER_PORT:8080}

minio-adapter:
  bucket: gridcapa
  base-path:
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000